spring.application.name=ecommerce

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://marwanramiz:marwanramiz2007@ecommerce-cluster.uigx1dk.mongodb.net/ecommerce?retryWrites=true&w=majority
spring.data.mongodb.database=ecommerce
